### ISSUE TITLE
Windows test users needed!

### ISSUE THREAD

**Issue by simonwhitaker** [simonwhitaker/gibo-go#1]
I need some folks to test this out on Windows. The hope is that it "just works" and in future I can maintain a single `gibo` codebase for all OSs.

## How to test

Download the appropriate zip file of [the latest release](https://github.com/simonwhitaker/gibo-go/releases), unzip, then run `gibo-go.exe` in a terminal window.

## Things to test

- [x] `gibo-go` should show help information
- [x] `gibo-go update` should complete successfully, and result in a local clone of https://github.com/github/gitignore in the directory shown by running `gibo-go root`
- [x] `gibo-go list` should show a list of available packages
- [x] `gibo-go list` should show its output in columns when outputting to a terminal, but not when outputting to e.g. a file, or a pipe to another command

**Comment by simonwhitaker** [comment]
@kai2nenobu @kodybrown you two have [contributed to `gibo.bat` in the past](https://github.com/simonwhitaker/gibo/commits/main/gibo.bat). Tagging you in case you'd be interested in helping with the next generation of gibo!

**Comment by simonwhitaker** [comment]
OK, I tested this by using [this site](https://learn.microsoft.com/en-us/training/modules/implement-common-integration-features-finance-ops/10-exercise-1) to spin up a Windows VM.

![Capture-2023-07-16-22817 pm](https://github.com/simonwhitaker/gibo-go/assets/116432/a585f389-b8fd-450b-b441-54fb8e75581d)

<img width="990" alt="Screenshot 2023-07-16 at 2 29 38 pm" src="https://github.com/simonwhitaker/gibo-go/assets/116432/6ab03917-3cac-4a48-a1de-46a330b9a826">

**Comment by kai2nenobu** [comment]
@simonwhitaker Very nice work👍 I tested `gibo-go` in my Windows 10 machine and `gibo-go` works almost perfectly. A migration from v2 to v3 is very seamless!

I found small problems, then I'll report in other issues.

**Comment by simonwhitaker** [comment]
Thanks so much @kai2nenobu !
