### ISSUE TITLE
Behavior change of search command between gibo-go and gibo.bat

### ISSUE THREAD

**Issue by kai2nenobu** [simonwhitaker/gibo-go#3]
## Problem

There is a behavior change between `gibo-go search` and `gibo.bat search`. `gibo.bat search` searches **contents of boilerplates**.

```console
> gibo.bat search py
Autotools.gitignore:6:/py-compile
CodeIgniter.gitignore:12:user_guide_src/cilexer/pycilexer.egg-info/*
community\DotNet\core.gitignore:5:*.pyc
community\LensStudio.gitignore:12:# Python #
community\LensStudio.gitignore:13:__pycache__/
community\LensStudio.gitignore:14:*.py[cod]
...
```

On the other hands, `gibo-go search` searches **names of boilerplates**.

```console
> gibo-go search py
Python
JupyterNotebooks
```

If this is an intentional change, there is no problem.

## Runtime environment

```
gibo.bat version: 2.2
gibo-go version: gibo-go.exe v3.0.0, commit a95405b8972cc1f407bb573d7f4f1130bd1e6938, built on 2023-07-17T18:54:47Z
OS: Windows 10 (Build 19045.3208)
```

**Comment by simonwhitaker** [comment]
Ah, I had no idea gibo.bat did this! 😄 Plain old gibo has only ever searched filenames. I'll close this one for now, but I'll consider this as a feature request for the future.
